apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmksc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmksc
  template:
    metadata:
      labels:
        app: bmksc
    spec:
      containers:
      - image: okteto.dev/bmksc:latest
        name: bmksc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "051f3a58-3ed5-4417-9c77-81f0570b7ca0"
        - name: Vless_Path
          value: "/vl55nf5"
        - name: Vmess_UUID
          value: "051f3a58-3ed5-4417-9c77-81f0570b7ca0"
        - name: Vmess_Path
          value: "/vm6sgr6"
        - name: Share_Path
          value: "/v2link"
